---

- name: Unzip the Slurm accounting DB
  unarchive:
    src: "{{ slurmdb_dump_file_path }}"
    dest: /home/centos/

- name: Modify the table names in the database dump file to match dev setup
  command: perl -pi.bak -e 's/slurm_cluster/ohpc/g;' /home/centos/slurmdb_backup_20191014_032723

- name: Stop the slurmdbd service before restoring the dump file into new database
  command: systemctl stop slurmdbd

- name: Drop the existing slurm accounting database
  command: mysql -u root -e "drop database slurmdb;"

- name: Create new database with the name defined in the slurm config
  command: mysql -u root -e "create database slurmdb;"

- name: Restore the database from the modified backup file.
  mysql_db:
    state: import
    name: slurmdb
    target: /home/centos/slurmdb_backup_20191014_032723

- name: Start slurmdbd manually
  command: slurmdbd -vvvv

- name: Pause for slurm db daemon to rollup.
  pause:
    seconds: 180

