---

- name: Update Shorewall rules for SSH and sshpiper
  ansible.builtin.blockinfile:
    path: /etc/shorewall/rules
    insertbefore: "^#LAST LINE"
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    backup: true
    block: |
      # -- Allow port 2222 traffic for SSH from internet to master
      ACCEPT:info   net            fw              tcp     2222

- name: Restart Shorewall
  ansible.builtin.service:
    name: shorewall
    state: restarted
