---
- name: Clone template repo from upstream
  git:
    repo: '{{ rstudio_ood_repo }}'
    dest: '/var/www/ood/apps/sys/bc_rstudio_server'
    force: yes
    version: master 

- name: Replace form.yml
  template:
    src: form.yml
    dest: /var/www/ood/apps/sys/bc_rstudio_server/form.yml

- name: Replace form submission template
  copy:
    src: submit.yml
    dest: /var/www/ood/apps/sys/bc_rstudio_server/submit.yml.erb

- name: Replace manifest file
  copy:
    src: manifest.yml
    dest: /var/www/ood/apps/sys/bc_rstudio_server/manifest.yml

- name: Replace script.sh.erb file
  copy:
    src: script.sh.erb.j2
    dest: /var/www/ood/apps/sys/bc_rstudio_server/template/script.sh.erb
