---
- name: Copy the configure file for apps
  template:
    src: "{{ item }}/env_local.j2"
    dest: "/var/www/ood/apps/sys/{{ item }}/.env.local"
  with_items:
    - dashboard
    - myjobs
    - shell

- name: Add initializers folder
  file:
    path: /etc/ood/config/apps/dashboard/initializers
    state: directory

- name: Add shared directories into files menu
  template:
    src: dashboard/ood_rb.j2
    dest: /etc/ood/config/apps/dashboard/initializers/ood.rb

- name: Add cheaha favicon image
  copy:
    src: favicon.ico
    dest: "/var/www/ood/public"

- name: Add cheaha logo image
  copy:
    src: "{{ ood_dashboard_logo_filename }}"
    dest: "/var/www/ood/public"

- name: Restart apps to pickup new settings
  shell: |
    touch /var/www/ood/apps/sys/{{ item }}/tmp/restart.txt
  with_items:
    - dashboard
    - myjobs

- name: Put motd in place
  template:
    src: motd.j2
    dest: /etc/ood/motd
