---
- name: Change the default min UID and GID to replicate prod
  lineinfile:
    path: /etc/login.defs
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  loop:
    - { regexp: '^UID_MIN\t{3}1000', line: 'UID_MIN\t{3}10000' }
    - { regexp: '^GID_MIN\t{3}1000', line: 'GID_MIN\t{3}10000' }

- name: Create .agent_db dir for sqlite DB if not present
  file:
    path: /cm/shared/rabbitmq_agents/.agent_db
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Clone the repo where user ldap files are recorded
  git:
    repo: "{{ rc_users_ldap_repo }}"
    dest: "{{ rc_users_ldap_repo_loc }}"
  ignore_errors: yes 
  register: result

#- debug:
#    msg: "{{ result }}"
#  when: result.rc!=0

- name: "Error: {{ result.stderr_lines[0] }}"
  fail:
    msg: You need to upload the ssh key to "{{ rc_users_ldap_repo }}"
  when:  result.rc!=0

