---
- name: Set SELinux to permissive mode
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Install prerequisite pkgs
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - gcc

- name: Download Go
  get_url:
    url: "{{ go_download_url }}"
    dest: "{{ go_download_path }}"

- name: Extract Go
  ansible.builtin.unarchive:
    src: "{{ go_download_path }}" 
    dest: "{{ go_binary_path }}"
    remote_src: yes

- name: Set Go path
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export PATH=$PATH:{{ go_binary_path }}/go/bin"
    state: present

- name: Clone sshpiper repository
  ansible.builtin.git:
    repo: "{{ sshpiper_git_repo }}"
    version: "{{ sshpiper_version }}"
    dest: "{{ sshpiper_dest_dir }}"
    update: true
    recursive: true

- name: Create output directory for sshpiper
  ansible.builtin.file:
    path: "{{sshpiper_bin_dir}}"
    state: directory

- name: Build sshpiper
  ansible.builtin.command: go build -tags full -o out ./...
  args:
    chdir: "{{sshpiper_dest_dir}}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{go_binary_path}}/go/bin"
    CGO_ENABLED: 1

- name: Change SSH port to 2222
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port '
    line: 'Port 2222'

- name: Restart SSH service
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Configure sshpiper yaml plugin
  ansible.builtin.template:
    src: sshpiperd.yaml.j2
    dest: "{{ sshpiper_dest_dir }}/sshpiperd.yaml"
    backup: true

- name: Install systemd service file for sshpiper
  ansible.builtin.template:
    src: sshpiperd.service.j2
    dest: /etc/systemd/system/sshpiperd.service
    backup: true

- name: Enable and start sshpiper service
  ansible.builtin.service:
    name: sshpiperd
    enabled: yes
    state: started

