---
- name: Remove existing RStudio app install
  file:
    path: "{{ ood_sys_apps_dir }}/bc_rstudio_server"
    state: absent

- name: Create RStudio app directory
  file:
    path: "{{ ood_sys_apps_dir }}/bc_rstudio_server"
    state: directory

- name: Clone template repo from upstream
  git:
    repo: "{{ rstudio_ood_app_repo }}"
    dest: "{{ ood_sys_apps_dir }}/bc_rstudio_server"
    refspec: "{{ rstudio_ood_app_refspec }}"
    version: "{{ rstudio_ood_app_version }}"
